"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RivalOffset = exports.LastOffset = exports.OptionOffset = exports.CommonOffset = void 0;
var CommonOffset;
(function (CommonOffset) {
    CommonOffset[CommonOffset["AREA"] = 1] = "AREA";
    CommonOffset[CommonOffset["SEQ_HEX"] = 1] = "SEQ_HEX";
    CommonOffset[CommonOffset["WEIGHT_DISPLAY"] = 3] = "WEIGHT_DISPLAY";
    CommonOffset[CommonOffset["CHARACTER"] = 4] = "CHARACTER";
    CommonOffset[CommonOffset["EXTRA_CHARGE"] = 5] = "EXTRA_CHARGE";
    CommonOffset[CommonOffset["TOTAL_PLAYS"] = 9] = "TOTAL_PLAYS";
    CommonOffset[CommonOffset["SINGLE_PLAYS"] = 11] = "SINGLE_PLAYS";
    CommonOffset[CommonOffset["DOUBLE_PLAYS"] = 12] = "DOUBLE_PLAYS";
    CommonOffset[CommonOffset["WEIGHT"] = 17] = "WEIGHT";
    CommonOffset[CommonOffset["NAME"] = 25] = "NAME";
    CommonOffset[CommonOffset["SEQ"] = 26] = "SEQ";
})(CommonOffset || (exports.CommonOffset = CommonOffset = {}));
var OptionOffset;
(function (OptionOffset) {
    OptionOffset[OptionOffset["SPEED"] = 1] = "SPEED";
    OptionOffset[OptionOffset["BOOST"] = 2] = "BOOST";
    OptionOffset[OptionOffset["APPEARANCE"] = 3] = "APPEARANCE";
    OptionOffset[OptionOffset["TURN"] = 4] = "TURN";
    OptionOffset[OptionOffset["STEP_ZONE"] = 5] = "STEP_ZONE";
    OptionOffset[OptionOffset["SCROLL"] = 6] = "SCROLL";
    OptionOffset[OptionOffset["ARROW_COLOR"] = 7] = "ARROW_COLOR";
    OptionOffset[OptionOffset["CUT"] = 8] = "CUT";
    OptionOffset[OptionOffset["FREEZE"] = 9] = "FREEZE";
    OptionOffset[OptionOffset["JUMP"] = 10] = "JUMP";
    OptionOffset[OptionOffset["ARROW_SKIN"] = 11] = "ARROW_SKIN";
    OptionOffset[OptionOffset["FILTER"] = 12] = "FILTER";
    OptionOffset[OptionOffset["GUIDELINE"] = 13] = "GUIDELINE";
    OptionOffset[OptionOffset["GAUGE"] = 14] = "GAUGE";
    OptionOffset[OptionOffset["COMBO_POSITION"] = 15] = "COMBO_POSITION";
    OptionOffset[OptionOffset["FAST_SLOW"] = 16] = "FAST_SLOW";
})(OptionOffset || (exports.OptionOffset = OptionOffset = {}));
var LastOffset;
(function (LastOffset) {
    LastOffset[LastOffset["SONG"] = 3] = "SONG";
    LastOffset[LastOffset["CALORIES"] = 10] = "CALORIES";
})(LastOffset || (exports.LastOffset = LastOffset = {}));
var RivalOffset;
(function (RivalOffset) {
    RivalOffset[RivalOffset["RIVAL_1_ACTIVE"] = 1] = "RIVAL_1_ACTIVE";
    RivalOffset[RivalOffset["RIVAL_2_ACTIVE"] = 2] = "RIVAL_2_ACTIVE";
    RivalOffset[RivalOffset["RIVAL_3_ACTIVE"] = 3] = "RIVAL_3_ACTIVE";
    RivalOffset[RivalOffset["RIVAL_1_DDRCODE"] = 9] = "RIVAL_1_DDRCODE";
    RivalOffset[RivalOffset["RIVAL_2_DDRCODE"] = 10] = "RIVAL_2_DDRCODE";
    RivalOffset[RivalOffset["RIVAL_3_DDRCODE"] = 11] = "RIVAL_3_DDRCODE";
})(RivalOffset || (exports.RivalOffset = RivalOffset = {}));
